### PR TITLE
Updated Gluu documentation

### PR DESCRIPTION
**Pull request by hofmannedv**
Markup, spelling and grammar.

### CODE REVIEW

**Comment by hofmannedv** [comment]
Not merged after 17 days :/

**Comment by willow9886** [comment]
@hofmannedv I don't see a merge request... Can you resubmit, or did we get this merged?

**Comment by hofmannedv** [comment]
@willow9886 I think this pull request became part of #60. Everything seems to be fine now :)

**Comment by willow9886** [comment]
Great. Thanks, Frank.

**Pull request closed without merging**
